apiVersion: v1
kind: Event
metadata:
  name: event-11
  namespace: default
reason: "CreateNodredPod"
message: '{"podName": "nodered-7", "envs": {"FOO": "BAR", "NODE_ENV": "production"}}'
involvedObject:
  kind: RedEnvoy
  name: redenvoy-setup
  namespace: default
  apiVersion: apps.abstractprism.com/v1
type: Normal
source:
  component: "manual-trigger"