apiVersion: v1
kind: Event
metadata:
  name: delete-pod-event-2
  namespace: default
reason: "DeleteNoderedPod"
message: '{"podName": "nodered-7"}'
involvedObject:
  kind: RedEnvoy
  name: redenvoy-setup
  namespace: default
  apiVersion: apps.abstractprism.com/v1
type: Normal
source:
  component: "manual-trigger"