apiVersion: v1
kind: Event
metadata:
  name: delete-pod-event-2
  namespace: default
reason: "DeleteNoderedPod"
message: "nodered-7" # POD name or other relevant info
involvedObject:
  kind: RedEnvoy
  name: redenvoy-setup
  namespace: default
  apiVersion: apps.abstractprism.com/v1
type: Normal
source:
  component: "manual-trigger"