apiVersion: apps.abstractprism.com/v1
kind: RedEnvoy
metadata:
  name: redenvoy-setup
  namespace: default
  labels:
    app: redenvoy-setup
spec:
  containerImage: "nodered/node-red:latest-20"
  triggeredEventName: "CreateNodredPod"
  triggeredDeleteEventName: "DeleteNodredPod"
  containerPort: 1880
  ingressHost: "nodered.local"
